solution
mate-academy/js_todo pull request #37
Opened 2019-10-10 21:30 UTC by veronika-donets

2019-10-13 16:13 UTC, gestap commented on js_todo.js
> +    return console.log(this.list);
навіщо ти повертаєш console?

2019-10-13 16:13 UTC, gestap commented on js_todo.js
> +    return console.log(element[0] || `There is no work to do.`);
не повертай console

2019-10-15 07:25 UTC, 8hokage approved these changes

2019-10-15 08:02 UTC, 8hokage requested changes

2019-10-15 08:02 UTC, earthhuman41 commented on js_todo.js
> +    return element[0] || `There is no work to do.`;
Лучше делать проверку на пустой массив перед тем как сортируешь

2019-10-16 10:08 UTC, 8hokage approved these changes

2020-06-09 11:24 UTC, closed without merging