Kate`s solution
mate-academy/js_todo pull request #6
Opened 2019-06-02 13:23 UTC by ekaterinakur

[Preview] (https://ekaterinakur.github.io/js_todo/)

2019-06-04 10:28 UTC, ost-ptk requested changes

2019-06-04 10:28 UTC, gestap commented on src/index.html
> +    <script type="text/javascript" src="main.js"></script>
use 2 whitespaces instead of 4

2019-06-04 10:28 UTC, gestap commented on src/main.js
> +    if (item) { return item; }
https://github.com/mate-academy/style-guides/blob/master/javascript.md#blocks--braces

2019-06-04 18:04 UTC, ost-ptk requested changes

2019-06-04 18:04 UTC, gestap commented on src/main.js
> +class Todo {
use strict mode

2019-06-04 18:04 UTC, gestap commented on src/main.js
> +      return error.message;
you need to `...throw an error` instead return message

2019-06-05 18:51 UTC, ost-ptk approved these changes

2020-06-09 11:24 UTC, closed without merging